[BD-27] [TNL-7948] Fix Static File References
edx/cc2olx pull request #48
Opened 2021-02-18 11:48 UTC by aayushagra

We noticed that not all static links were escaped as part of the conversion process. This PR adds code to recursively process all input going into OLX nodes to automatically escape any static file references.

**JIRA tickets**: TNL-7948

**Merge deadline**: None

**Testing instructions**:

1. Download and try to import a course with static links in various places, including in multiple-choice problems answers (Where we found the problem), discussion topics & other locations
2. Convert the course with cc2olx and verify that all static links were escaped successfully

**Reviewers**
- [ ] @farhaanbukhsh

2021-02-18 11:48 UTC, edx-webhook commented
Thanks for the pull request, @aayushagra! I've created [BLENDED-772](https://openedx.atlassian.net/browse/BLENDED-772) to keep track of it in Jira.   More details are on the [BD-27](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1544912903/BD-27+Common+Cartridge+Converter) project page.


When this pull request is ready, tag your edX technical lead.


<!-- comment:welcome-blended -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2021-02-22 12:00 UTC, farhaanbukhsh requested changes
I have added few nits, I tested this and it looks good with the course in question. Good work :medal_military:

2021-02-22 15:15 UTC, farhaanbukhsh commented
@aayushagra  can you resolve the conflicts

2021-02-22 15:17 UTC, farhaanbukhsh requested changes
Some more nits :) please have a look.

2021-02-22 15:17 UTC, farhaanbukhsh commented on src/cc2olx/olx.py
> +        Output: {'problem_details': '<img src="/static/..."/> Lorem Ipsum', ...}
There is a specific format in which you should write the docstring. Have a look at https://github.com/edx/cc2olx/blob/master/src/cc2olx/filesystem.py#L19

2021-02-22 17:38 UTC, farhaanbukhsh approved these changes
👍 

- [x] I tested this with the course in question, able to import it properly
- [x] I read through the code
- [ ] ~~I checked for accessibility issues~~
- [ ] ~~Includes documentation~~
- [ ] ~~I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository.~~

2021-02-22 17:38 UTC, farhaanbukhsh commented on src/cc2olx/olx.py
> +            details: A dictionary or an array of dictionaries containing node data
```suggestion
            details: A dictionary or list of dictionaries containing node data.
```

2021-02-22 17:38 UTC, farhaanbukhsh commented on src/cc2olx/olx.py
> +                        inside it has been escaped to an OLX friendly format
```suggestion
        Returns:
            details: Returns detail data with static link
                        escaped to an OLX-friendly format.
```

2021-02-23 19:25 UTC, alangsto approved these changes

2021-02-23 19:26 UTC, merged